name: Ping Service

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping user-service
        run: curl -s -o /dev/null -w "%{http_code}" https://user-service-i41g.onrender.com/api/health || true
